development:
  adapter: postgresql
  encoding: unicode
  database: sc_rails_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sc_rails_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sc_rails_production
  pool: 5
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: sc_rails_staging
  pool: 5
  username: postgres
  password:

demo:
  adapter: postgresql
  encoding: unicode
  database: sc_rails_demo
  pool: 5
  username: postgres
  password: